name: gnezdo
description: book-exchange app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.8
  
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true